version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "54310:25565"
    environment:
      EULA: "TRUE" # ยอมรับข้อตกลงของ Mojang
      MEMORY: 5G # ปรับได้ตามเครื่องคุณ
      ENABLE_WHITELIST: "TRUE"
      WHITELIST: "H2oZn"
      MOTD: "Welcome to my Docker Minecraft Server!"
    volumes:
      - ./data:/data # ข้อมูลเซิร์ฟเวอร์จะถูกเก็บถาวร
    restart: unless-stopped
